version: '3'
services:

  website:
    container_name: website
    image: decentralgames-website:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.dev.decentral.games
    restart: always
    user: root
    ports:
      - "3000:3000"
