version: '3'
services:

  website:
    container_name: website
    image: decentralgames-website:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production # change this to adjust which environments APIs are called
    restart: always
    user: root
    ports:
      - "3000:3000"
