export const ACTION_PUT_BLOG = "ACTION_PUT_BLOG";

export const ACTION_SET_KEYWORD = "ACTION_SET_KEYWORD";
export const ACTION_SET_RESULT = "ACTION_SET_RESULT";
export const ACTION_SET_LOADING = "ACTION_SET_LOADING";
